In [6]:
import numpy as np
# import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go


def de(fobj, bounds, mut=0.8, crossp=0.7, popsize=20, its=1000):
    dimensions = len(bounds)
    pop = np.random.rand(popsize, dimensions)
    min_b, max_b = np.asarray(bounds).T
    diff = np.fabs(min_b - max_b)
    pop_denorm = min_b + pop * diff
    fitness = np.asarray([fobj(ind) for ind in pop_denorm])
    best_idx = np.argmin(fitness)
    best = pop_denorm[best_idx]
    for i in range(its):
        for j in range(popsize):
            idxs = [idx for idx in range(popsize) if idx != j]
            a, b, c = pop[np.random.choice(idxs, 3, replace=False)]
            mutant = np.clip(a + mut * (b - c), 0, 1)
            cross_points = np.random.rand(dimensions) < crossp
            if not np.any(cross_points):
                cross_points[np.random.randint(0, dimensions)] = True
            trial = np.where(cross_points, mutant, pop[j])
            trial_denorm = min_b + trial * diff
            f = fobj(trial_denorm)
            if f < fitness[j]:
                fitness[j] = f
                pop[j] = trial
                if f < fitness[best_idx]:
                    best_idx = j
                    best = trial_denorm
        yield best, fitness[best_idx]


result = list(de(lambda x: sum(x**2) / len(x), bounds=[(-100, 100)] * 32))
print(result[-1])


x, f = zip(*result)
# plt.plot(f)
# plt.show()
# fig = px.line(f)
# fig.show()
fig = go.Figure()

for d in [8, 16, 32, 64]:
    it = list(de(lambda x: sum(x**2)/d, [(-100, 100)] * d, its=3000))
    x, f = zip(*it)
    # plt.plot(f, label='d={}'.format(d))
    # fig.add_scatter(f, mode='lines')
    fig.add_trace(go.Scatter(y=f, mode='lines'))
# plt.legend()
# plt.show()

fig.show()


(array([-0.3329555 ,  1.11724462,  0.86418418, -1.18064431, -1.04784033,
        1.54072467,  2.67573525,  0.14831873,  3.8639941 , -2.58352352,
        1.4690399 ,  1.54613459, -1.15089866, -1.19372562, -4.594323  ,
       -4.1318453 , -2.34100674, -1.5365673 ,  0.39577277,  0.08643392,
        0.93361592, -1.00032998,  1.49305914, -0.66078991,  0.14417882,
       -1.18420197, -2.12219738,  3.27371309,  1.3077399 , -2.31312967,
        0.10932179, -1.72977927]), 3.7652765462275344)


In [2]:
f

(2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2268.729528790527,
 2257.701919963402,
 2257.701919963402,
 2257.701919963402,
 2257.701919963402,
 2257.701919963402,
 2257.419636860524,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1809.1304981643439,
 1678.4687494496613,
 1678.4687494496613,
 1678.4687494496613,
 1678.4687494496613,
 1678.4687494496613,
 1678.4687494496613,


In [3]:
x

(array([ -7.97446304,  -9.60068211,  91.10534478,  -5.13868015,
         84.92830981, -25.79661199,   0.6946426 , -26.57247721,
        -36.94217386,  82.6790922 ,  44.46157941,  24.38230632,
        -10.11496008,  33.85743656,  55.28466884,  24.7646464 ,
        -24.96262364, -43.65604352, -37.09087961,  81.46958125,
         81.11655874, -42.85149958, -13.70861447,  16.19948497,
         81.72850681,   3.49697281, -68.3387863 , -50.74736633,
         13.07247625,  74.91766371,  26.03202696,  -5.91112867]),
 array([ -7.97446304,  -9.60068211,  91.10534478,  -5.13868015,
         84.92830981, -25.79661199,   0.6946426 , -26.57247721,
        -36.94217386,  82.6790922 ,  44.46157941,  24.38230632,
        -10.11496008,  33.85743656,  55.28466884,  24.7646464 ,
        -24.96262364, -43.65604352, -37.09087961,  81.46958125,
         81.11655874, -42.85149958, -13.70861447,  16.19948497,
         81.72850681,   3.49697281, -68.3387863 , -50.74736633,
         13.07247625,  74.91766371,  2